name: Simple ESP32S3 Build Test

on:
  workflow_dispatch:  # 只允许手动触发
  
env:
  IDF_VERSION: 'v5.5.1'

jobs:
  simple-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git wget flex bison gperf python3 python3-venv cmake ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0
        
    - name: Download and setup ESP-IDF
      run: |
        echo "Downloading ESP-IDF ${{ env.IDF_VERSION }}..."
        git clone --recursive --depth 1 --branch ${{ env.IDF_VERSION }} https://github.com/espressif/esp-idf.git ~/esp-idf
        
        echo "Installing ESP-IDF for ESP32S3..."
        cd ~/esp-idf
        ./install.sh esp32s3
        
        echo "IDF_PATH=$HOME/esp-idf" >> $GITHUB_ENV
        
    - name: Test ESP-IDF setup
      run: |
        source $HOME/esp-idf/export.sh
        echo "ESP-IDF Path: $IDF_PATH"
        echo "Python version: $(python --version)"
        idf.py --version
        
    - name: Check project structure
      run: |
        echo "=== Project Structure ==="
        ls -la
        echo ""
        echo "=== Components ==="
        ls -la components/
        echo ""
        echo "=== Main component ==="
        ls -la main/
        
    - name: Simple configuration test
      run: |
        source $HOME/esp-idf/export.sh
        echo "Setting target to ESP32S3..."
        idf.py set-target esp32s3 -v
        
    - name: Build test
      run: |
        source $HOME/esp-idf/export.sh
        echo "Attempting build..."
        idf.py build -v